// Generated by CoffeeScript 1.5.0
(function() {
  var TumblrTicklr, findNextLine, fs, getLines, markAsUsed, nt, _;

  nt = require('ntumblr');

  fs = require('fs');

  _ = require('underscore');

  TumblrTicklr = function(postsTextFile, accessKey, accessSecret, blogName) {
    var lines, next;
    lines = getLines(postsTextFile);
    next = findNextLine(lines);
    console.log(next);
    if (next) {
      markAsUsed(postsTextFile, lines, next);
    }
    return next;
  };

  getLines = function(textFile) {
    return _.reject(fs.readFileSync(textFile, 'utf8').split('\n'), function(line) {
      return !line;
    });
  };

  findNextLine = function(lines) {
    var idx, line, _i, _len;
    console.log(lines);
    for (idx = _i = 0, _len = lines.length; _i < _len; idx = ++_i) {
      line = lines[idx];
      console.log(line, idx);
      if (line.match(/<-- current$/)) {
        return lines[idx + 1];
      }
    }
    return lines[0];
  };

  markAsUsed = function(textFile, lines, lineUsed) {
    var currentSeen, idx, line, _i, _len;
    currentSeen = 0;
    fs.renameSync(textFile, textFile + '.bak');
    for (idx = _i = 0, _len = lines.length; _i < _len; idx = ++_i) {
      line = lines[idx];
      if (line === lineUsed) {
        currentSeen = 1;
        lines[idx] = lineUsed + '<-- current';
      } else {
        if (!currentSeen) {
          lines[idx] = line.replace('<-- current', '');
        }
      }
    }
    return fs.writeFileSync(textFile, lines.join('\n'));
  };

  module.exports = TumblrTicklr;

}).call(this);
